[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "node scripts/deploy.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 90
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
USE_DATABASE = "true"

[nixpacks]
nodejs-version = "20"
apt-pkgs = ["ffmpeg", "python3", "python3-pip"]
installCommand = "npm ci --legacy-peer-deps"

# Install OpenAI Whisper during the build phase
[nixpacks.setup]
cmds = [
  "python3 -m pip install -U openai-whisper",
  "chmod +x ./install-whisper.sh",
  "./install-whisper.sh"
]

# Ensure the build directory structure is correct
[nixpacks.build]
cmds = [
  "chmod +x ./fix-build.js"
]

# Configure environment variables for PostgreSQL
[variables]
DATABASE_URL.fromService = { service = "postgresql", type = "connectionString" }
PGHOST.fromService = { service = "postgresql", name = "host" }
PGDATABASE.fromService = { service = "postgresql", name = "database" }
PGUSER.fromService = { service = "postgresql", name = "username" }
PGPASSWORD.fromService = { service = "postgresql", name = "password" }
PGPORT.fromService = { service = "postgresql", name = "port" }
NODE_ENV = "production" 