[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[nixpacks]
nodejs-version = "20"
apt-pkgs = ["ffmpeg", "python3", "python3-pip"]

# Install OpenAI Whisper during the build phase
[nixpacks.setup]
cmds = [
  "python3 -m pip install -U openai-whisper",
  "chmod +x ./install-whisper.sh",
  "./install-whisper.sh"
] 